baseURL = "https://guillermoandraefisher.com"
languageCode = "en-us"
title = "The life and times of Guillermo A. Fisher"
enableRobotsTXT = true
ignoreErrors = [ "error-disable-taxonomy" ]
disableKinds = [ "taxonomy" ]

[module]
    [[module.imports]]
        path = "github.com/guillermoandrae/hugo-bklyn"
