description = "The life and times of Guillermo A. Fisher"
shortName = "Guillermo"
author = "Guillermo A. Fisher"

############## BANNER ##############
[banner]
message = "Black Lives Matter, even during a pandemic."
link = "https://757colorcoded.org/allyship"
cta = "Learn how you can make a difference."

############## GOOGLE ##############
[google]
siteVerificationId = "gD3PYmVi5Mh_W5JVtZa9Ifu4jsl4xyayCERwX2dVVYQ"
analyticsId = "UA-7964669-2"

############## SOCIAL MEDIA ##############
[[social]]
title = "Spotify"
icon = "fa-spotify"
link = "https://open.spotify.com/user/1213990935"

[[social]]
title = "Twitter"
icon = "fa-twitter"
link = "https://twitter.com/guillermoandrae"

[[social]]
title = "Pinterest"
icon = "fa-pinterest"
link = "https://pinterest.com/guillermoandrae"

[[social]]
title = "Instagram"
icon = "fa-instagram"
link = "https://instagram.com/guillermoandrae"

[[social]]
title = "Medium"
icon = "fa-medium"
link = "https://medium.com/@guillermoandrae"

[[social]]
title = "GitHub"
icon = "fa-github"
link = "https://github.com/guillermoandrae"

[[social]]
title = "LinkedIn"
icon = "fa-linkedin"
link = "https://linkedin.com/in/guillermoandrae"

############## PLUGINS ##############
[[ plugins.js ]]
url = "js/links.js"

[[ plugins.js ]]
url = "js/search.js"

[[ plugins.js ]]
url = "js/covid.js"
