dist: xenial
language: node_js
cache:
  directories:
  - node_modules
script:
- npm install
deploy:
  provider: s3
  bucket: guillermoandraefisher.com
  local_dir: dist
  skip_cleanup: true
  region: us-east-1
  acl: public_read
  on:
    repo: guillermoandrae/guillermo
  secret_access_key:
    secure: OG+y0r5QeHF0SQsTMAZlo2+smefPbate/SIx8u+Zyy5hHxN0/+oMVUdmfB1FjMLOTIieLcWOigdaB8QGDlq0UCZwMJsx3HLjnQWmWVz87451D3ad9YXQnfr9jQeNNruhsPSutGvJSlaqGp3f2pBhSWBpuFYFIfFnGHMwgRkJ8jfqFeJ3UPU1LzZN3JFekuXdtELBr91wiAtou1Owhr4x62S4AABsKel8UhJnAcEL2r9Qn0d5ZR8j4oIsX8mPGoS8X2RbNUMZRggBJiSABRP7k7tvZrBP10UgYqAMDKbY0FIVdotQZbfihOUDhxR7fFRRhCh2Gd3dJr79D9qaMuGMg9d2ravOltJZHHwaQblcta6YaFnSOjvZic8R0zJLQiOD6SOjJN/pRKpQ14c0V8GFZjBnr5kiDsnRpO3oY0Ow1rRyAbITWmF/mKQYSH7B/VZSIYXNBy2zrd5w1AkoxfOaekAPeMgyUG97CxH1xLrxZkl+8P3sXIVZwF7UNpOcKESwYwmRqV5GkfjOPaNUtHNbeiVPeuNGmgFAIj0uw+98HWWXBaBigq4agQymagsdZTgOpOHYkLwEe9hHWgXfD2U6+Viyr0ScXBXHz7n9SxFxhZT6RT9XWLTaOlezWKS0rH36grmNPCskhtpuOCUAUFCqGZVWnViG9Uc7drKwbdMsO9s=
  access_key_id:
    secure: IuZ0AzEVUdHf+BLsFeCP9oFU+gILAmh3HklcleEkYwKrCOW7pumTFcK6SK4egVzPMM+npTfilnSQDMNKU3DtN8SkMVtPgmmLLyKQ4/HHUfbbBsvuL7EaJmAZEm3if1zp0C/dcRacvsa0UIejNLnoLZvfJHN3jZsqsPS7RYeOkmTbeSERlp0XHp3ckB9YG0Zg9nCRrKoNRwWhVCf6mDJeRXja1f0AqWDRNVPwi/kZdFieUCb5MNd4yyHAt/RCd7g3wP6rx36eaPzNrFI08pQj+dVOrR+E2FI0CIDYgdQpOab66lG42WEpWpqXIQe6G3Fx4ByjmROrV9UDDg8NbI11ryo+qvhK/tYGmAKZIHeyIqCb6QYfIjrXNVxY0bM/gzzCQAjISQ4zpU3D0WIiuqSLXFvWPTOBmjxiJ9ynTmrfkURa3KNJjlaxJ68Wrud9PdvxRTDXrKEu98/NiMUJ8Dvd0sEaB7Qx8ESD3I3fpfF2DQlbYOJnKAdaA/+uWLt1Ql/S2keM3EeG3Ph0ZQef5eO5M4cc2lYirX0IMdbX3303oNNTs30cdtW6afbytVDuHMYojvmteSq5OWMSPzdmyolrK+VV5OXsqtZuf770HmlkrjIuKaWIwB0f+axz8R2+HsGtNcowWSHwcktKURMRRJkCb3lfHlmhLP8HV7q6Szh36dE=
