openapi: 3.0.3
info:
  title: Posts
  description: Posts
  version: 1.0.0
servers:
  - url: https://api.guillermoandraefisher.com
components:
  schemas:
    Post:
      type: object
      properties:
        externalId:
          type: string
        platform:
          type: string
        originalAuthor:
          type: string
        createdAt:
          type: integer
          format: int64
        thumbnailUrl:
          type: string
        htmlUrl:
          type: string
        body:
          type: string
  parameters:
    limit:
      name: limit
      in: query
      description: max records to return
      required: false
      schema:
        type: integer
        format: int32
  responses:
    PostsList:
      description: posts
      content:
        application/json:
          schema:
            type: object
            properties:
              meta:
                type: object
                properties:
                  count:
                    type: integer
                    format: int32
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'

paths:
  /posts:
    get:
      summary: Returns posts
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/responses/PostsList'

